# Configuration automatique de la source de données Prometheus pour Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    withCredentials: false
    editable: true
    orgId: 1
    version: 1
